version: "3.8"
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
  my-people-service:
    build: .
    ports:
      - "9090:8080"
    environment:
      - spring.data.mongodb.host=mongodb
    depends_on:
      - mongodb